<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IN-DB5PTN3" failures="0" tests="4" name="TestCases.Certification.Certi_RatingAndPricing_TC" time="0.234" errors="1" timestamp="2023-11-08T12:01:42 IST" skipped="3">
  <testcase classname="TestCases.Certification.Certi_RatingAndPricing_TC" name="configure" time="0.234">
    <error message="io/restassured/path/xml/mapper/factory/JakartaEEObjectMapperFactory" type="java.lang.NoClassDefFoundError">
      <![CDATA[java.lang.NoClassDefFoundError: io/restassured/path/xml/mapper/factory/JakartaEEObjectMapperFactory
at io.restassured.config.RestAssuredConfig.<init>(RestAssuredConfig.java:41)
at io.restassured.RestAssured.<clinit>(RestAssured.java:422)
at com.MSIL.Setup.RestAssuredSetup.configure(RestAssuredSetup.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.ClassNotFoundException: io.restassured.path.xml.mapper.factory.JakartaEEObjectMapperFactory
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
... 22 more
]]>
    </error>
  </testcase> <!-- configure -->
  <system-out/>
  <testcase classname="TestCases.Certification.Certi_RatingAndPricing_TC" name="Rating_And_Pricing" time="0.000">
    <skipped/>
  </testcase> <!-- Rating_And_Pricing -->
  <system-out/>
  <testcase classname="TestCases.Certification.Certi_RatingAndPricing_TC" name="Rating_And_Pricing" time="0.000">
    <skipped/>
  </testcase> <!-- Rating_And_Pricing -->
  <system-out/>
  <testcase classname="TestCases.Certification.Certi_RatingAndPricing_TC" name="Rating_And_Pricing" time="0.000">
    <skipped/>
  </testcase> <!-- Rating_And_Pricing -->
  <system-out/>
</testsuite> <!-- TestCases.Certification.Certi_RatingAndPricing_TC -->
